### ISSUE TITLE
Is linux supported?

### ISSUE THREAD

**Issue by ckir** [SimoneAncona/simply2d#2]

**Comment by SimoneAncona** [comment]
I'm currently working on making it Linux compatible, there are some issues with the SDL2 binaries

**Comment by SimoneAncona** [comment]
Version 1.0.7 supports Linux but is still in beta

**Comment by SimoneAncona** [comment]
Version 1.0.9 should fix any Linux compatibility issues, if you have any other issues feel free to send more feedback
